import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/src/context/AuthContext";
import { AuthModal } from "@/src/components/auth/AuthModal";
import { AppChrome } from "@/src/components/layout/AppChrome";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <div className="flex min-h-screen flex-col bg-slate-50 text-slate-900">
          <AuthProvider>
            <AppChrome>{children}</AppChrome>
            <AuthModal />
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
